# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        environment: [development, production]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Google Chrome headless
      run: |
        sudo apt-get update -y
        sudo apt-get install -y google-chrome-stable

    - name: Set CHROME_BIN headless
      run: echo "CHROME_BIN=/usr/bin/google-chrome" >> $GITHUB_ENV

    - name: Build the Angular app for ${{ matrix.environment }}
      run: |
        if [ "${{ matrix.environment }}" == "production" ]; then
          npm run build;
        else
          npm run build -- --configuration=development;
        fi

    - name: Run tests
      run: npm test
        env:
        CHROME_BIN: "/usr/bin/google-chrome"
